#!/usr/bin/env python3
"""Audit the new 200-row LOO campaign without selecting favorable results.

One family: four PIDs x four deletions x two metrics = 32 paired tests.
All intervals are descriptive paired bootstrap intervals, not simultaneous.
"""
from __future__ import annotations

import argparse
import hashlib
import itertools
import json
from datetime import datetime, timezone
from pathlib import Path

import numpy as np
import pandas as pd
from scipy.stats import rankdata

import run_rebuilt_loo_ablation as runner

PROTOCOL = {"pids": [1, 6, 10, 14], "pin": 1, "dim": 20, "repeats": 10,
            "budget_scale": 1.0, "seed_base": 20260808}
METRICS = ("rpr", "f1")


def paired_exact_signed_rank(differences: np.ndarray) -> float:
    """Two-sided exact sign permutation, average tied ranks; discard zeros.

    Values are rounded to 12 decimals only for zero/tie recognition in this
    test. Means, deltas and intervals use the unrounded original values.
    """
    differences = np.round(np.asarray(differences, dtype=float), 12)
    nonzero = differences[differences != 0]
    if not len(nonzero):
        return 1.0
    ranks = rankdata(np.abs(nonzero), method="average")
    observed = abs(float(np.dot(np.sign(nonzero), ranks)))
    signs = np.asarray(list(itertools.product((-1, 1), repeat=len(nonzero))))
    return float(np.mean(np.abs(signs @ ranks) >= observed - 1e-12))


def holm(pvalues: np.ndarray) -> np.ndarray:
    order = np.argsort(pvalues, kind="stable")
    adjusted = np.maximum.accumulate((len(order) - np.arange(len(order))) * pvalues[order])
    result = np.empty(len(order))
    result[order] = np.minimum(adjusted, 1.0)
    return result


def self_check(data: pd.DataFrame) -> dict:
    runner.validate_frame(data, PROTOCOL)
    cases = {}
    cases["missing_condition"] = data[data.config != "RMC-NoMaximin"].copy()
    cases["missing_entire_pair"] = data[~((data.pid == 1) & (data.repeat == 1))].copy()
    cases["duplicate_key"] = pd.concat([data, data.iloc[[0]]], ignore_index=True)
    cases["paired_seed_mismatch"] = data.copy()
    cases["paired_seed_mismatch"].loc[0, "seed"] += 1
    cases["nan_metric"] = data.copy()
    cases["nan_metric"].loc[0, "rpr"] = np.nan
    cases["budget_overrun"] = data.copy()
    cases["budget_overrun"].loc[0, "used_eval"] = 400001
    cases["missing_diagnostic"] = data.drop(columns="mrmc_relation_uses")
    cases["activated_disabled_path"] = data.copy()
    index = cases["activated_disabled_path"].index[cases["activated_disabled_path"].config == "RMC-NoRelations"][0]
    cases["activated_disabled_path"].loc[index, "mrmc_relation_uses"] = 1
    cases["negative_diagnostic"] = data.copy()
    cases["negative_diagnostic"].loc[0, "mrmc_working_promotions"] = -1
    failures = {}
    for name, changed in cases.items():
        try:
            runner.validate_frame(changed, PROTOCOL)
        except (ValueError, RuntimeError) as exc:
            failures[name] = str(exc)
        else:
            raise AssertionError(f"invalid synthetic campaign passed: {name}")
    try:
        runner.strict_stats({})
    except RuntimeError:
        failures["worker_missing_diagnostics"] = "strict_stats rejects absent counters"
    else:
        raise AssertionError("missing diagnostics silently accepted")
    assert paired_exact_signed_rank(np.ones(10)) == 2 / 1024
    assert paired_exact_signed_rank(np.zeros(10)) == 1
    assert paired_exact_signed_rank(np.array([1, -1])) == 1
    assert np.allclose(holm(np.array([0.01, 0.04, 0.03])), [0.03, 0.06, 0.06])
    return {"valid_input_passed": True, "synthetic_invalid_inputs_rejected": failures,
            "signed_rank_and_holm_reference_cases_passed": True}


def write_tex_tables(folder: Path, data: pd.DataFrame, comparisons: pd.DataFrame) -> None:
    folder.mkdir(parents=True, exist_ok=True)
    labels = {"RMC-CMSA": "Full", "RMC-NoMaximin": "No maximin", "RMC-NoRelations": "No relations",
              "RMC-NoTerminalMemory": "No terminal memory", "RMC-NoTrajectoryEvidence": "No trajectory evidence"}
    end = r" \\" + "\n"
    table = "% Generated by code/pipeline/analyze_rebuilt_loo.py; sample SD; pooled rows are descriptive means.\n"
    table += r"\begin{tabular}{llrrrrr}" + "\n" + r"\toprule" + "\n"
    table += "PID & Metric & " + " & ".join(labels[c] for c in runner.LOO_CONFIGS) + end + r"\midrule" + "\n"
    for pid in PROTOCOL["pids"]:
        for metric in METRICS:
            cells = []
            for config in runner.LOO_CONFIGS:
                values = data.loc[(data.pid == pid) & (data.config == config), metric]
                cells.append(f"${values.mean():.3f} \\pm {values.std(ddof=1):.3f}$")
            table += f"{pid} & {metric.upper()} & " + " & ".join(cells) + end
    table += r"\midrule" + "\n"
    for metric in METRICS:
        table += f"Pooled & {metric.upper()} & " + " & ".join(f"{data.loc[data.config == c, metric].mean():.3f}" for c in runner.LOO_CONFIGS) + end
    table += r"\bottomrule" + "\n" + r"\end{tabular}" + "\n"
    (folder / "rebuilt_loo_ablation.tex").write_text(table, encoding="utf-8")
    table = "% Generated by analyze_rebuilt_loo.py. Terminal peak is the sum of per-run peaks.\n"
    table += r"\begin{tabular}{lrrrrr}" + "\n" + r"\toprule" + "\n"
    table += "Configuration & Relation uses & Maximin selections & Sum of terminal peaks & Evidence observations & Runs" + end + r"\midrule" + "\n"
    counters = ("mrmc_relation_uses", "mrmc_maximin_selections", "mrmc_terminal_memory_peak", "mrmc_evidence_observed")
    for config in runner.LOO_CONFIGS:
        group = data[data.config == config]
        table += labels[config] + " & " + " & ".join(f"{int(group[c].sum()):,}" for c in counters) + f" & {len(group)}" + end
    table += r"\bottomrule" + "\n" + r"\end{tabular}" + "\n"
    (folder / "rebuilt_loo_diagnostics.tex").write_text(table, encoding="utf-8")
    table = "% Generated by analyze_rebuilt_loo.py. Delta = Full minus deletion. One Holm family of 32.\n"
    table += r"\begin{tabular}{lllrrr}" + "\n" + r"\toprule" + "\n"
    table += r"PID & Deletion & Metric & $\Delta$ & $p_{\rm raw}$ & $p_{\rm Holm}$" + end + r"\midrule" + "\n"
    for row in comparisons.itertuples():
        table += f"{row.pid} & {labels[row.deletion]} & {row.metric.upper()} & {row.mean_delta_full_minus_deletion:+.4f} & {row.p_two_sided_exact_signed_rank:.4f} & {row.p_holm_32:.4f}" + end
    table += r"\bottomrule" + "\n" + r"\end{tabular}" + "\n"
    (folder / "rebuilt_loo_paired.tex").write_text(table, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--input", type=Path, default=runner.ROOT / "results/ablation/rebuilt_loo_selected.csv")
    parser.add_argument("--outdir", type=Path, default=runner.ROOT / "results/ablation/analysis")
    parser.add_argument("--bootstrap-draws", type=int, default=50000)
    parser.add_argument("--tex-dir", type=Path, default=runner.ROOT / "paper/tables_edc")
    parser.add_argument("--self-check", action="store_true")
    args = parser.parse_args()
    if args.bootstrap_draws < 1000:
        parser.error("at least 1000 bootstrap draws are required")
    data = pd.read_csv(args.input)
    validation = runner.validate_frame(data, PROTOCOL)
    args.outdir.mkdir(parents=True, exist_ok=True)
    checks = self_check(data) if args.self_check else None
    summaries = []
    for (pid, config), group in data.groupby(["pid", "config"]):
        row = {"pid": int(pid), "config": config, "n": len(group)}
        for metric in METRICS:
            row.update({metric + "_mean": float(group[metric].mean()), metric + "_sd": float(group[metric].std(ddof=1))})
        row["used_eval_mean"] = float(group.used_eval.mean())
        summaries.append(row)
    pd.DataFrame(summaries).to_csv(args.outdir / "rebuilt_loo_per_pid_summary.csv", index=False)
    overall = data.groupby("config")[list(METRICS)].mean().reindex(runner.LOO_CONFIGS)
    overall.to_csv(args.outdir / "rebuilt_loo_descriptive_overall.csv")
    diagnostics = data.groupby(["pid", "config"])[list(runner.COUNTERS)].sum()
    diagnostics.to_csv(args.outdir / "rebuilt_loo_diagnostic_sums.csv")
    comparisons = []
    for pid in PROTOCOL["pids"]:
        case = data[data.pid == pid]
        full = case[case.config == "RMC-CMSA"].set_index("repeat").sort_index()
        for deletion in runner.LOO_CONFIGS[1:]:
            other = case[case.config == deletion].set_index("repeat").sort_index()
            for metric in METRICS:
                differences = (full[metric] - other[metric]).to_numpy(dtype=float)
                seedtext = f"rmc-loo-ci-v1|{pid}|{deletion}|{metric}"
                seed = int.from_bytes(hashlib.blake2b(seedtext.encode(), digest_size=8).digest(), "little")
                rng = np.random.default_rng(seed)
                indices = rng.integers(0, len(differences), size=(args.bootstrap_draws, len(differences)))
                lo, hi = np.quantile(differences[indices].mean(axis=1), [0.025, 0.975])
                comparisons.append({"pid": pid, "deletion": deletion, "metric": metric, "n_pairs": len(differences),
                                    "full_mean": float(full[metric].mean()), "deletion_mean": float(other[metric].mean()),
                                    "mean_delta_full_minus_deletion": float(differences.mean()),
                                    "bootstrap_95_low_unadjusted": float(lo), "bootstrap_95_high_unadjusted": float(hi),
                                    "full_wins": int((differences > 1e-12).sum()), "ties": int((np.abs(differences) <= 1e-12).sum()),
                                    "full_losses": int((differences < -1e-12).sum()),
                                    "p_two_sided_exact_signed_rank": paired_exact_signed_rank(differences)})
    comparisons = pd.DataFrame(comparisons)
    assert len(comparisons) == 32
    comparisons["p_holm_32"] = holm(comparisons.p_two_sided_exact_signed_rank.to_numpy())
    comparisons["reject_holm_005"] = comparisons.p_holm_32 <= 0.05
    comparisons.to_csv(args.outdir / "rebuilt_loo_paired_comparisons.csv", index=False)
    write_tex_tables(args.tex_dir, data, comparisons)
    inputs = {"file": args.input.name, "sha256": runner.sha256(args.input), "rows": len(data),
              "run_manifest_available_for_input": False, "raw_solutions_available_for_input": False}
    manifest = {"created_utc": datetime.now(timezone.utc).isoformat(), "input": inputs,
                "protocol_checked": PROTOCOL, "analysis_environment": runner.environment(),
                "analysis_script_sha256": runner.sha256(Path(__file__).resolve()),
                "current_validator_sha256": runner.sha256(Path(runner.__file__).resolve()),
                "validation": validation, "self_checks": checks,
                "test": "two-sided exact sign permutation of Wilcoxon average signed ranks; discard zero differences; ties recognized at 12 decimals",
                "test_assumption": "independent seed pairs and symmetry/sign exchangeability of paired differences under the null",
                "multiplicity": "one Holm family of 32 comparisons: 4 PIDs x 4 deletions x RPR/F1",
                "confidence_intervals": f"paired nonparametric percentile bootstrap; {args.bootstrap_draws} resamples; deterministic hash-derived seeds; descriptive unadjusted 95% intervals",
                "no_pooled_test": "overall means are descriptive only; heterogeneous PIDs were not pooled for significance testing",
                "historical_provenance_limit": "current analysis metadata do not reconstruct the unavailable original run environment or raw solution archives"}
    runner.json_write(args.outdir / "rebuilt_loo_analysis_manifest.json", manifest)
    nsignificant = int(comparisons.reject_holm_005.sum())
    minp = float(comparisons.p_holm_32.min())
    audit = f"""# 新逐组件消融审计 / Audit of the new matched LOO campaign

## 数据与边界 / Data and scope

本分析仅使用 rebuilt_loo_selected.csv 的 200 行：PIDs 1、6、10、14，D=20，instance=1，10 个配对种子，5 个配置，每次上限 400,000 次评估。旧压缩包 formal_single_deletion 的 2,400 行、与新样本重叠的 pilot，以及工程 smoke 均未合并。选定四个问题的依据未在运行前的可核验协议中记录，因此这是探索性补充，不能视为完整 16 题确认性证据。

Only the new 200-row selected-case campaign is analyzed. Historical results, overlapping pilots and engineering smoke runs are excluded. No verifiable pre-run rationale for selecting these four cases was captured; this is exploratory evidence, not a confirmatory full-suite study.

已有 200 行缺少运行时 manifest 和最终解向量，无法事后补造。当前分析环境与分析源码哈希记录在 JSON 中，不等同于原运行环境。新 runner 今后在运行前保存协议、全部相关源码/数据哈希、环境，并保存每次的最终解向量与全部诊断；未记录逐代轨迹。

The 200 rows have no contemporaneous run manifest or returned-vector archive. Current analysis provenance is recorded separately. Future runs save a pre-run manifest, final decision vectors and full diagnostics, but no per-generation trace.

## 统计方法 / Statistical method

对每个 PID 独立比较 Full 与四个删除条件的 RPR、F1，共 32 个双侧配对精确符号置换 Wilcoxon 检验，统一 Holm 校正。零差删除，绝对差并列用平均秩；只在零差/并列识别时保留 12 位小数。检验假设是种子对独立，零假设下配对差满足符号可交换性/对称性。均差使用原精度。95% 区间来自 {args.bootstrap_draws:,} 次配对 percentile bootstrap，仅作描述，未作多重校正；n=10，精度有限。总体均值不用于合并显著性检验。

There are 32 within-PID, two-sided exact signed-rank sign-permutation tests, with a single Holm family. Zero differences are discarded and ties use average ranks. The null requires independent seed pairs and sign exchangeability/symmetry. Bootstrap intervals are descriptive and unadjusted; no pooled across-problem test is used.

## 结果 / Results

Holm 校正后显著比较为 {nsignificant}/32，最小校正 p={minp:.6g}。完整方法没有稳定优于每个删除条件。以下总体均值保留不利结果：

| Configuration | Mean RPR | Mean F1 |
|---|---:|---:|
"""
    for config, row in overall.iterrows():
        audit += f"| {config} | {row.rpr:.5f} | {row.f1:.5f} |\n"
    audit += """

Full–NoMaximin 在 PID1 的 RPR 均差为 +0.08；Full–NoTrajectoryEvidence 在 PID10 为 +0.11，而在 PID14 为 -0.07。应同时呈现这些差异，不能据此宣称所有模块都有独立显著收益。

Full shows case-dependent benefits and losses: the RPR differences above favor Full on PID1/NoMaximin and PID10/NoTrajectoryEvidence but favor the deletion on PID14/NoTrajectoryEvidence. This evidence does not establish an independently significant benefit for every component.

## 控制检查与代码修复 / Controls and runner fixes

冻结算法核心未改。NoRelations 将关系候选替换为等量均匀候选；NoMaximin 随机选候选；NoTerminalMemory 关闭终止记忆读写；NoTrajectoryEvidence 关闭观测和注入。200 行所有关闭路径计数为零，启用组件在各相应配置整体被触发。Full 工作记忆在 38/40 次运行中激活，但全部 200 行 working_promotions 均为零；不能将路径计数当成因果贡献或晋升收益。

The frozen core is unchanged. Matched deletions disable the intended paths; enabled paths are exercised at campaign level. Full working memory is active in 38/40 runs, but working promotions are zero in all 200 runs. Path access does not prove causal influence or promotion benefit.

修复范围是 runner：固定五条件、执行后自动验证、缺失诊断直接报错、完整网格和配对种子/预算检查、禁用路径断言、运行前 manifest、与源码/环境匹配的续跑保护、逐运行原始解存档。旧无 manifest CSV 只能 validate-only，不能追加。小预算 smoke 仅校验工程路径，可不触发所有组件，并显式标记 engineering_smoke。

The runner now enforces five conditions, automatic validation, strict counters, the complete planned grid, paired seeds, budget checks, disabled-path assertions, source/environment-compatible resume, and raw returned-vector artifacts. Existing unmanifested CSVs are validate-only. Tiny smoke runs are labeled engineering-only and may leave enabled paths dormant.

模块之间仍存在合理交互：删除 maximin 后，终止记忆即使被读取，也未必影响随机选择。这不是开关失效，也不应通过追求显著性来改写算法。另一个历史 ladder 对照中候选数不等，未在本次修改中修正，也未作为组件独立贡献的证据。

Component interactions remain: with maximin removed, computed terminal-memory scores may no longer influence random selection. This does not imply a defective switch. The separate ladder comparison has a candidate-pool-size confound; it is unchanged and is not used here as isolated component evidence.
"""
    engineering_checks = args.outdir / "rebuilt_loo_engineering_checks.json"
    if engineering_checks.exists():
        audit += """

## 工程核验 / Engineering verification

独立工程 campaign：PID1、D=5、1 个种子、5 条件、每次 10,000 次评估上限（实际 9,942--9,950）。五个配置均完成，启用组件整体触发，禁用计数为零。保存的最终解（每次 5--6 个）及目标值可以离线重算，并与 CSV 的 RPR/F1 一致。相同协议重启跳过全部 5 个已验证结果；更改预算的续跑、追加无历史 manifest 的 200 行 CSV、非五配置 CLI 都被拒绝。数值自检另覆盖缺行/整对缺失、重复键、错配种子、NaN、超预算、缺失/负数诊断、禁用路径被触发。详情见 rebuilt_loo_engineering_checks.json 与 analysis manifest。这 5 行不属于统计样本。

An independent engineering campaign used PID1, D=5, one seed and five conditions at a 10,000-evaluation limit. It completed all conditions and retained 5--6 final vectors per run. Saved objective values and RPR/F1 agree with offline rescoring. An unchanged resume skipped all five verified rows; changed-budget resume, append to legacy unmanifested data and non-five-condition commands were rejected. Additional synthetic validation failures are documented in the analysis manifest. These five smoke rows are excluded from the 200-row study.

Reproduce the statistical analysis and its checks:

```text
python -B code/pipeline/analyze_rebuilt_loo.py --self-check
```

Run a new engineering campaign (choose a new output name if the source hashes have changed):

```text
python -B code/pipeline/run_rebuilt_loo_ablation.py --pids 1 --dim 5 --repeats 1 --budget-scale 0.1 --workers 1 --engineering-smoke --out results/ablation/analysis/rebuilt_loo_engineering_release.csv
```

Validate the existing 200 rows without appending or claiming retroactive runtime provenance:

```text
python -B code/pipeline/run_rebuilt_loo_ablation.py --pids 1 6 10 14 --dim 20 --repeats 10 --out results/ablation/rebuilt_loo_selected.csv --validate-only
```
"""
    (args.outdir / "rebuilt_loo_audit_zh_en.md").write_text(audit, encoding="utf-8")
    print(json.dumps({"rows": len(data), "comparisons": len(comparisons), "holm_significant": nsignificant,
                      "minimum_holm_p": minp, "outputs": str(args.outdir), "self_checks": checks}, indent=2))


if __name__ == "__main__":
    main()
